name: satemirova_sport_psy
description: "Psycological game for sport"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: >=3.4.0 <4.0.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  cupertino_icons: ^1.0.8
  provider: ^6.0.5
  shared_preferences: ^2.1.1
  image_picker: ^1.1.2   # ðŸ“¸ Ð´Ð»Ñ Ð²Ñ‹Ð±Ð¾Ñ€Ð° Ñ„Ð¾Ñ‚Ð¾ Ð¸Ð· Ð³Ð°Ð»ÐµÑ€ÐµÐ¸ Ð¸Ð»Ð¸ ÐºÐ°Ð¼ÐµÑ€Ñ‹

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  intl_utils: ^2.8.8

flutter:
  uses-material-design: true
  assets:
    - lib/l10n/intl_en.arb
    - lib/l10n/intl_ru.arb
    - lib/l10n/intl_kk.arb

flutter_intl:
  enabled: true
  arb_dir: lib/l10n
  output_dir: lib/generated
  template_arbs:
    - lib/l10n/intl_en.arb
